[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.stripe.com; style-src 'self' 'unsafe-inline' https://api.mapbox.com https://fonts.cdnfonts.com https://fonts.googleapis.com; font-src 'self' https://fonts.cdnfonts.com https://fonts.gstatic.com data:; img-src 'self' data: blob: https://*.supabase.co https://api.mapbox.com https://*.stripe.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.stripe.com; frame-src 'self' https://*.stripe.com;"

[build.environment]
  VITE_TOKEN_ECONOMY_SCHEMA = "token_economy"
